# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Stories of Machine Learning
tagline:           
url:              https://mohakrajendra.github.io
paginate:         1
baseurl:          /
author:
  name:           Mohak Rajendra
  url:            http://mohakr.brandyourself.com/
  email:          mohakraaj@gmail.com

# Custom vars
<<<<<<< HEAD
repo:           https://github.com/mohakrajendra?tab=repositories
linkedIn:       http://ca.linkedin.com/pub/mohak-rajendra/29/893/531/en	
=======
version:          1.0.0
repo:           https://github.com/mohakrajendra
linkedIn:       https://ca.linkedin.com/pub/mohak-rajendra/29/893/531/en	
>>>>>>> origin/master


pages_list:       
  Archive: '/archive'
  About: '/about'

