# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Stories of Machine Learning
tagline:           
url:              https://mohakrajendra.github.io
paginate:         1
baseurl:          /
author:
  name:           Mohak Rajendra
  url:            https://twitter.com/
  email:          mohakraaj@gmail.com

# Custom vars
version:          1.0.0
  repo:           https://github.com/mohakrajendra
  linkedIn:       https://ca.linkedin.com/pub/mohak-rajendra/29/893/531/en	


pages_list:       
  About: '/about'
  Archive: '/archive'

